import { ROUTES } from '@/constants/routes'

const MENU_MAIN = [
    {
        id: 2,
        name: ROUTES.overview.format_name,
        routeName: ROUTES.overview.name,
        open: false,
        paramsNames: [],
        icon: null,
    }, {
        id: 3,
        name: ROUTES.benefits.format_name,
        routeName: ROUTES.benefits.name,
        open: false,
        paramsNames: [],
        icon: null,
    },
]

const MENU_DASHBOARDS = [
    {
        id: 5,
        name: ROUTES.analytics.format_name,
        routeName: ROUTES.analytics.name,
        open: false,
        paramsNames: [],
        subMenu: [
            {
                id: 6,
                name: ROUTES.campaign_comparison.format_name,
                routeName: ROUTES.campaign_comparison.name,
                open: false,
                paramsNames: [],
                icon: null,
            }, {
                id: 7,
                name: ROUTES.metrics_costs_conversions_roi.format_name,
                routeName: ROUTES.metrics_costs_conversions_roi.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
    {
        id: 8,
        name: ROUTES.ads_efficiency.format_name,
        routeName: ROUTES.ads_efficiency.name,
        open: false,
        paramsNames: [],
        subMenu: [
            {
                id: 9,
                name: ROUTES.ad_efficiency_google.format_name,
                routeName: ROUTES.ad_efficiency_google.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 10,
                name: ROUTES.ad_efficiency_facebook.format_name,
                routeName: ROUTES.ad_efficiency_facebook.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 11,
                name: ROUTES.ad_efficiency_instagram.format_name,
                routeName: ROUTES.ad_efficiency_instagram.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 12,
                name: ROUTES.ad_efficiency_linkedin.format_name,
                routeName: ROUTES.ad_efficiency_linkedin.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 13,
                name: ROUTES.ad_efficiency_twitter.format_name,
                routeName: ROUTES.ad_efficiency_twitter.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 14,
                name: ROUTES.ad_efficiency_pinterest.format_name,
                routeName: ROUTES.ad_efficiency_pinterest.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 15,
                name: ROUTES.ad_efficiency_yandex.format_name,
                routeName: ROUTES.ad_efficiency_yandex.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
    {
        id: 16,
        name: ROUTES.email_marketing_efficiency.format_name,
        routeName: ROUTES.email_marketing_efficiency.name,
        open: false,
        paramsNames: [],
        subMenu: [
            {
                id: 17,
                name: ROUTES.email_marketing_mailchimp_efficiency.format_name,
                routeName: ROUTES.email_marketing_mailchimp_efficiency.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 18,
                name: ROUTES.email_marketing_sendinblue_efficiency.format_name,
                routeName: ROUTES.email_marketing_sendinblue_efficiency.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
    {
        id: 19,
        name: ROUTES.a_b_testing_efficiency.format_name,
        routeName: ROUTES.a_b_testing_efficiency.name,
        paramsNames: [],
        subMenu: [
            {
                id: 20,
                name: ROUTES.test_results_efficiency.format_name,
                routeName: ROUTES.test_results_efficiency.name,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
]

const MIDDLE_MENU = [
    {
        id: 21,
        name: ROUTES.ad_campaigns.format_name,
        routeName: ROUTES.ad_campaigns.name,
        subMenu: [
            {
                id: 22,
                name: ROUTES.google_ads.format_name,
                routeName: ROUTES.google_ads.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 23,
                name: ROUTES.facebook_ads.format_name,
                routeName: ROUTES.facebook_ads.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 24,
                name: ROUTES.instagram_ads.format_name,
                routeName: ROUTES.instagram_ads.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 25,
                name: ROUTES.linkedin_ads.format_name,
                routeName: ROUTES.linkedin_ads.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 26,
                name: ROUTES.twitter_ads.format_name,
                routeName: ROUTES.twitter_ads.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 27,
                name: ROUTES.pinterest_ads.format_name,
                routeName: ROUTES.pinterest_ads.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 28,
                name: ROUTES.yandex_direct.format_name,
                routeName: ROUTES.yandex_direct.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        paramsNames: [],
        icon: null,
    },
    {
        id: 29,
        name: ROUTES.email_marketing.format_name,
        routeName: ROUTES.email_marketing.name,
        paramsNames: [],
        subMenu: [{
            id: 30,
            name: ROUTES.mailchimp.format_name,
            routeName: ROUTES.mailchimp.name,
            open: false,
            paramsNames: [],
            icon: null,
        },
            {
                id: 31,
                name: ROUTES.sendin_blue.format_name,
                routeName: ROUTES.sendin_blue.name,
                open: false,
                paramsNames: [],
                icon: null,
            }],
        icon: null,
    },
    {
        id: 32,
        name: ROUTES.optimization.format_name,
        routeName: ROUTES.optimization.name,
        paramsNames: [],
        subMenu: [{
            id: 33,
            name: ROUTES.optimization_a_b_testing.format_name,
            routeName: ROUTES.optimization_a_b_testing.name,
            open: false,
            paramsNames: [],
            icon: null,
        },
            {
                id: 34,
                name: ROUTES.optimization_analytics_and_reports.format_name,
                routeName: ROUTES.optimization_analytics_and_reports.name,
                open: false,
                paramsNames: [],
                icon: null,
            }],
        icon: null,
    },
]

const MENU_BOTTOM = [
    {
        id: 35,
        name: ROUTES.integrations.format_name,
        routeName: ROUTES.integrations.name,
        paramsNames: [],
        subMenu: [
            {
                id: 36,
                name: ROUTES.available_integrations.format_name,
                routeName: ROUTES.available_integrations.name,
                open: false,
                paramsNames: [],
                icon: null,
            }, {
                id: 37,
                name: ROUTES.setup_integrations.format_name,
                routeName: ROUTES.setup_integrations.name,
                open: false,
                paramsNames: [],
                icon: null,
            }],
        icon: null,
    }, {
        id: 38,
        name: ROUTES.documentation.format_name,
        routeName: ROUTES.documentation.name,
        paramsNames: [],
        subMenu: [
            {
                id: 39,
                name: ROUTES.guides.format_name,
                routeName: ROUTES.guides.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 40,
                name: ROUTES.api_documentation.format_name,
                routeName: ROUTES.api_documentation.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 41,
                name: ROUTES.faq.format_name,
                routeName: ROUTES.faq.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
    {
        id: 42,
        name: ROUTES.blog.format_name,
        routeName: ROUTES.blog.name,
        paramsNames: [],
        subMenu: [
            {
                id: 43,
                name: ROUTES.marketing_articles.format_name,
                routeName: ROUTES.marketing_articles.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 44,
                name: ROUTES.use_cases.format_name,
                routeName: ROUTES.use_cases.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 45,
                name: ROUTES.news_and_updates.format_name,
                routeName: ROUTES.news_and_updates.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
    {
        id: 46,
        name: ROUTES.support.format_name,
        routeName: ROUTES.support.name,
        paramsNames: [],
        subMenu: [
            {
                id: 47,
                name: ROUTES.contact_info.format_name,
                routeName: ROUTES.contact_info.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 48,
                name: ROUTES.support_chat.format_name,
                routeName: ROUTES.support_chat.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 49,
                name: ROUTES.ticket_system.format_name,
                routeName: ROUTES.ticket_system.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
    {
        id: 50,
        name: ROUTES.user_account.format_name,
        routeName: ROUTES.user_account.name,
        paramsNames: [],
        subMenu: [
            {
                id: 51,
                name: ROUTES.user_profile.format_name,
                routeName: ROUTES.user_profile.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 52,
                name: ROUTES.account_settings.format_name,
                routeName: ROUTES.account_settings.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
            {
                id: 53,
                name: ROUTES.activity_history.format_name,
                routeName: ROUTES.activity_history.name,
                open: false,
                paramsNames: [],
                icon: null,
            },
        ],
        icon: null,
    },
]

export {
    MENU_MAIN,
    MIDDLE_MENU,
    MENU_DASHBOARDS,
    MENU_BOTTOM,
}
